
file_create:
    path: /{id}/create
    defaults: { _controller: 'GedBundle:File:create'}

file_show:
    path: /{id}/show
    defaults: { _controller: 'GedBundle:File:show'}

file_edit:
    path: /{id}/edit
    defaults: { _controller: 'GedBundle:File:edit'}

#file_remove:
#    path: /{id}/remove
#    defaults: { _controller: 'GedBundle:File:remove' }

file_lock:
    path: /{id}/fileLock
    defaults: { _controller: 'GedBundle:File:lock' }
    options:
        expose: true

file_unlock:
    path: /{id}/fileLock
    defaults: { _controller: 'GedBundle:File:unlock' }
    options:
        expose: true