
version_create:
    path: /{id}/create
    defaults: { _controller: 'GedBundle:Version:create' }

version_download:
    path: /{id}/download
    defaults: { _controller: 'GedBundle:File:downloadVersion'}

version_view:
    path: /{id}/view
    defaults: { _controller: 'GedBundle:File:viewVersion'}