
parameters:
    ged_bundle.navbar_user_listener.class: GedBundle\EventListener\NavbarUserListener

services:
    my_admin_bundle.show_user_listener:
        class: %ged_bundle.navbar_user_listener.class%
        arguments:
            - @security.token_storage
        tags:
            - { name: kernel.event_listener, event: theme.navbar_user, method: onShowUser }

    ged_bundle.file_voter:
        class: GedBundle\Security\FileVoter
        arguments: [ @doctrine.orm.entity_manager ]
        tags:
            - { name: security.voter }

        public: false

    ged_bundle.logout_handler:
        class: GedBundle\Security\LogoutHandler
        arguments: [ @doctrine.orm.entity_manager ]

    ged_bundle.notifier:
        class: GedBundle\Utils\Notifier
        arguments: [@mailer, @templating]

    ged_bundle.notification_listener:
        class: GedBundle\EventListener\NotificationListener
        arguments: [@ged_bundle.notifier, @doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_listener, event: gedBundle.add_version, method: notifyAddVersion }
            - { name: kernel.event_listener, event: gedBundle.remove_version, method: notifyRemoveVersion }
            - { name: kernel.event_listener, event: gedBundle.remove_file, method: notifyRemoveFile }
            - { name: kernel.event_listener, event: gedBundle.remove_folder, method: notifyRemoveFolder }
