
parameters:
    ged_bundle.navbar_user_listener.class: GedBundle\EventListener\NavbarUserListener

services:
    my_admin_bundle.show_user_listener:
        class: %ged_bundle.navbar_user_listener.class%
        arguments:
            - @security.token_storage
        tags:
            - { name: kernel.event_listener, event: theme.navbar_user, method: onShowUser }

    ged_bundle.file_voter:
        class: GedBundle\Security\FileVoter
        arguments: [ @doctrine.orm.entity_manager ]
        tags:
            - { name: security.voter }

        public: false

    ged_bundle.logout_handler:
       class: GedBundle\Security\LogoutHandler
       arguments: [ @doctrine.orm.entity_manager ]