ged_bundle_file:
    resource: '@GedBundle/Resources/config/Routing/File.yml'
    prefix: /file

ged_bundle_folder:
    resource: '@GedBundle/Resources/config/Routing/Folder.yml'
    prefix: /folder

ged_bundle_version:
    resource: '@GedBundle/Resources/config/Routing/Version.yml'
    prefix: /version

ged_bundle_tag:
    resource: '@GedBundle/Resources/config/Routing/Tag.yml'
    prefix: /tag

ged_bundle_comment:
    resource: '@GedBundle/Resources/config/Routing/Comment.yml'
    prefix: /comment

ged_bundle_batch:
    resource: '@GedBundle/Resources/config/Routing/Batch.yml'
    prefix: /batch

