ged_bundle_file:
    resource: '@GedBundle/Resources/config/Routing/File.yml'
    prefix: /file

ged_bundle_folder:
    resource: '@GedBundle/Resources/config/Routing/Folder.yml'
    prefix: /folder

ged_bundle_workspace:
    resource: '@GedBundle/Resources/config/Routing/Workspace.yml'
    prefix: /workspace

ged_bundle_version:
    resource: '@GedBundle/Resources/config/Routing/Version.yml'
    prefix: /version

ged_bundle_tag:
    resource: '@GedBundle/Resources/config/Routing/Tag.yml'
    prefix: /tag

ged_bundle_comment:
    resource: '@GedBundle/Resources/config/Routing/Comment.yml'
    prefix: /comment

ged_bundel_user:
    resource: '@GedBundle/Resources/config/Routing/User.yml'
    prefix: /user

ged_bundle_group:
    resource: '@GedBundle/Resources/config/Routing/Group.yml'
    prefix: /group

ged_bundle_permission:
    resource: '@GedBundle/Resources/config/Routing/Permission.yml'
    prefix: /permission

ged_bundle_batch:
    resource: '@GedBundle/Resources/config/Routing/Batch.yml'
    prefix: /batch

ged_bundle_search:
    resource: '@GedBundle/Resources/config/Routing/Search.yml'
    prefix: /search

ged_bundle_mail:
    resource: '@GedBundle/Resources/config/Routing/Mail.yml'
    prefix: /mail

