<?php

namespace GedBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function findCommentsByFile($id, $limit)
    {
        $qb = $this->createQueryBuilder('c')
                ->leftJoin('c.file', 'f')
                ->leftJoin('c.createdBy', 'u')
                ->addSelect('u')
                ->where('f.id = :id')
                ->setParameter('id', $id)
                ->orderBy('c.created', 'DESC')
                ->setMaxResults($limit);

        return $qb->getQuery()
                    ->getResult();

    }


    public function findAllCommentsByFile($id)
    {
        $qb = $this->createQueryBuilder('c')
            ->leftJoin('c.file', 'f')
            ->leftJoin('c.createdBy', 'u')
            ->addSelect('u')
            ->where('f.id = :id')
            ->setParameter('id', $id);

        return $qb->getQuery()
            ->getResult();

    }
}
