<?php

namespace GedBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends EntityRepository
{

    public function findFileIdByFolderId($id)
    {

        $qb = $this->createQueryBuilder('fi')
                ->select('fi.id')
                ->leftJoin('fi.folder', 'fo')
                ->where('fo.id = :id')
                ->setParameter('id', $id);

        return $qb->getQuery()
                    ->getResult();

    }

    public function findFileByFolder($id)
    {

        $qb = $this->createQueryBuilder('fi')
            ->select('fi')
            ->leftJoin('fi.folder', 'fo')
            ->where('fo.id = :id')
            ->setParameter('id', $id);

        return $qb->getQuery()
            ->getResult();

    }

    public function findFileUser($id)
    {
        $qb = $this->createQueryBuilder('fi')
                ->leftJoin('fi.folder', 'fo')
                ->where('fo.id = :id')
                ->leftJoin('fi.createdBy', 'crt')
                ->leftJoin('fi.updatedBy', 'upd')
                ->addSelect('crt')
                ->addSelect('upd')
                ->setParameter('id', $id);

        return $qb->getQuery()
                    ->getArrayResult();
    }

    public function findWorkspaceFile($wk, $f)
    {
        $qb = $this->createQueryBuilder('f')
            ->from('GedBundle:WorkspaceFile', 'wf')
            ->Join('wf.file', 'foo')
            ->where('f.folder = :id')
            ->andWhere('foo.id = f.id')
            ->andWhere('wf.workspace = :wk')
            ->select('f.id')
            ->setParameter('id', $f)
            ->setParameter('wk', $wk)
        ;

        $result =  $qb->getQuery()->getResult();
        $fileIds = array();
        foreach( $result as $id )
        {
            array_push($fileIds, $id['id']);
        }

        return $fileIds;

    }

    public function findCreators($id)
    {
        $qb = $this->_em->createQueryBuilder()
            ->from('GedBundle:File', 'fi')
            ->from('GedBundle:User', 'usr')
            ->select('usr')
            ->distinct()
            ->where('fi.createdBy = usr.id')
            ->andWhere('fi.id = :id')
            ->setParameter('id', $id);

        return $qb->getQuery()
            ->getResult();
    }

    public function findTagsName($id)
    {
        $qb = $this->createQueryBuilder('fi')
            ->leftJoin('fi.tags', 'tg')
            ->addSelect('tg')
            ->where('fi.id = :id')
            ->setParameter('id', $id);

        return $qb->getQuery()
            ->getScalarResult();
    }

    public function searchFileByTag($tag)
    {
        $qb = $this->createQueryBuilder('f')
                ->leftJoin('f.tags', 'tg')
                ->setParameter('term', '%'.$tag.'%')
                ->where('tg.name LIKE :term')
                ->distinct('f.id');

        return $qb->getQuery()->getResult();
    }

    public function searchByName($name)
    {
        $qb = $this->createQueryBuilder('f')
                ->setParameter('term', '%'.$name.'%')
                ->where('f.name LIKE :term')
                ->leftJoin('f.createdBy', 'crt')
                ->leftJoin('f.updatedBy', 'upd')
                ->addSelect('crt')
                ->addSelect('upd');

        return $qb->getQuery()->getResult();


    }

}
