<?php

namespace GedBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Gedmo\Tree\Traits


/**
 * FolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FolderRepository extends EntityRepository
{
}
