<?php

namespace GedBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;
/**
 * FolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FolderRepository extends NestedTreeRepository
{
    public function findFiles($id)
    {
        $qb = $this->createQueryBuilder('fo')
            ->where('fo.id = :id')
            ->leftJoin('fo.files', 'fi')
            ->addSelect('fi')
            ->setParameter('id', $id)
        ;

        return $qb->getQuery()
                ->getResult();
    }

    public function findFolderUser($id)
    {
        $qb = $this->createQueryBuilder('fo')
            ->where('fo.id = :id')
            ->leftJoin('fo.createdBy', 'crt')
            ->leftJoin('fo.updatedBy', 'upd')
            ->addSelect('crt')
            ->addSelect('upd')
            ->setParameter('id', $id)
        ;

        return $qb->getQuery()
                    ->getArrayResult();
    }

    public function findFolderChildrenUser($id)
    {
        $qb = $this->createQueryBuilder('fo')
            ->leftJoin('fo.parent', 'pa')
            ->leftJoin('fo.createdBy', 'crt')
            ->leftJoin('fo.updatedBy', 'upd')
            ->where('pa.id = :id')
            ->addSelect('crt')
            ->addSelect('upd')
            ->setParameter('id', $id)
        ;

        return $qb->getQuery()
                ->getArrayResult();

    }
}
