<?php

namespace GedBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GroupeFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeFileRepository extends EntityRepository
{
    public function findGroupFileByFile($id)
    {
        $qb = $this->createQueryBuilder('gf')
            ->leftJoin('gf.file', 'f')
            ->leftJoin('gf.groupe', 'gp')
            ->addSelect('gp')
            ->where('f.id = :id')
            ->setParameter('id', $id);

        // To see late

        return $qb->getQuery()->getResult();
    }

    public function findGroupIds($id)
    {
        $qb = $this->createQueryBuilder('gf')
            ->leftJoin('gf.file', 'f')
            ->leftJoin('gf.groupe', 'gp')
            ->distinct()
            ->select('gp.id')
            ->where('f.id = :id')
            ->setParameter('id', $id);


        return $qb->getQuery()->getResult();
    }

    public function findGroupFileByGroup($id)
    {
        $qb = $this->createQueryBuilder('gf')
                ->leftJoin('gf.groupe', 'g')
                ->where('g.id = :id')
                ->setParameter('id', $id);

        return $qb->getQuery()->getResult();
    }

}
