<?php

namespace GedBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeRepository extends EntityRepository
{
    public function findNode($id)
    {
        $qb = $this->createQueryBuilder('no')
            ->where('no.id = :id')
            ->leftJoin('no.createdBy', 'crt')
            ->leftJoin('no.updatedBy', 'upd')
            ->addSelect('crt')
            ->addSelect('upd')
            ->setParameter('id', $id)
        ;

        return $qb->getQuery()
            ->getResult();
    }
}
