<?php

namespace GedBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OnHoldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OnHoldRepository extends EntityRepository
{
}
