<?php

namespace GedBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function countNodes($id)
    {
        $qb = $this->createQueryBuilder('t')
            ->select('COUNT(t.id)')
            ->innerJoin('t.files', 'fi')
            ->where('t.id = :id')
            ->setParameter('id', $id);

        return $qb->getQuery()
            ->getSingleScalarResult();
    }

    public function findTagsByFile($id)
    {
        $qb = $this->createQueryBuilder('t')
                ->select('t')
                ->innerJoin('t.files', 'fi')
                ->where('fi.id = :id')
                ->setParameter('id', $id);

        return $qb->getQuery()
                    ->getResult();
    }

    public function findAllTags()
    {
        $qb = $this->createQueryBuilder('t')
                ->select('t.name as value')
                ->addSelect('t.name as data')
                ->distinct();

        return $qb->getQuery()->getResult();
    }
}
