<?php

namespace GedBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function countNodes($id)
    {
        $qb = $this->createQueryBuilder('t')
            ->select('t')
            ->leftJoin('t.nodes', 'n')
            ->where('t.id = :id')
            ->setParameter('id', $id);

        return $qb->getQuery()
            ->getSingleResult();
    }
}
