<?php

namespace GedBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WorkspaceFolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkspaceFolderRepository extends EntityRepository
{

    public function findFoldersByWorkspace($id)
    {
        $qb = $this->createQueryBuilder('wf')
            ->leftJoin('wf.workspace', 'w')
            ->leftJoin('wf.folder', 'f')
            ->setParameter('id', $id)
            ->where('w.id = :id')
            ->addSelect('f');

        return $qb->getQuery()->getResult();
    }

    public function findSubscribedEmail($id)
    {
        $qb = $this->createQueryBuilder('wf')
            ->setParameter('id', $id)
            ->where('wf.folder = :id')
            ->andWhere('wf.notification > 0')
            ->leftJoin('wf.workspace', 'w')
            ->leftJoin('w.user', 'u')
            ->addSelect('u.email');

        return $qb->getQuery()->getResult();
    }


}
